### ISSUE TITLE
Syntaxe error symbole "newline"

### ISSUE THREAD

**Issue by olielvewen** [adrienmetais/adl#2]
@adrienmetais 

Hi,

I 've just discovered your software for my file epub downloaded for my sister (in fact a dirty file .acsm).

After downloaded it on my Manjaro, I've tried to run your CLI program following your advice and I get an error (before and after to change permission i.e chmod +x adl.py)

Here the error:

```
[olivier@thorielle Ebook]$ ./adl.py login <-u xxxxxxxxxxxxxx@gmail.com>
bash: erreur de syntaxe près du symbole inattendu « newline »
[olivier@thorielle Ebook]$ 
```

**Comment by adrienmetais** [comment]
Hello,

There was indeed a typo in the README, thanks for pointing it out !

I would like to add however, that < and > indicate that this is a placeholder that you must replace by a value (here, the Adobe ID). They should not be typed in the command.

More info on "standard" special characters in command line help here: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key

**Comment by olielvewen** [comment]
Hi Adrien,

Thanks a lot for resolving this typo error. However, this issue is still present and with the output error.

```
[olivier@thorielle adl]$ ./adl.py login -u <xxxxxxxxxxxxxx@gmail.com>
bash: erreur de syntaxe près du symbole inattendu « newline »
```

**Comment by adrienmetais** [comment]
Hello Olivier,

You should replace < adobeID > with your adobe ID, **without** the <>.
Try something like:
`./adl.py login -u xxxxxxxxxxxxxx@gmail.com`

**Comment by olielvewen** [comment]
This time I get this error.

```
[olivier@thorielle adl]$ ./adl.py login -u xxxxxxxxxxxxxx@gmail.com 
Password: 
Traceback (most recent call last):
  File "/home/olivier/Ebook/adl/./adl.py", line 109, in <module>
    args.func(args)
  File "/home/olivier/Ebook/adl/./adl.py", line 29, in adobe_login
    login.login(args.user, password)
  File "/home/olivier/Ebook/adl/adl/login.py", line 17, in login
    data.config = Config()
NameError: name 'Config' is not defined
```

Like password I type this one which is linked with the Adobe Id Account. An idea ?

 French Adrien ?

**Comment by adrienmetais** [comment]
Hello Olivier,

Yes, French ;) 
But I prefer to continue in English as this is public and could help another user !

I had broken some stuff for first-time users in my last updates, so please try with the latest version.

Thanks

**Comment by olielvewen** [comment]
Hi Adrien, ^\_^

Okay that's works fine. And absolute paths works fines.

However, In my case, I get two files named (Ils ne sont pas très originaux) two files in the same folder. The second has an number into two brackets and I get an error. If I remove the first and rename the second (i.e URLLink(1).acsm in URLLink.acsm that 's okay.

I put all the command lines for others:

```
[olivier@thorielle adl]$ ./adl.py login -u xxxxxxxxxxxxxx@gmail.com 
Password: 
[olivier@thorielle adl]$ ./adl.py get -f /home/olivier/Ebook/URLLink.acsm
INFO:Opening /home/olivier/Ebook/URLLink.acsm ...
INFO:Sending fullfilment request
INFO:Downloading Les chroniques de Bane T.10 : À la poursuite de l’amour from https://kbget1-a.akamaihd.net/koboid-prod-public/editis-epub-97a049e2-3422-4758-bffd-f47084e2fd58.epub ...
INFO:Patching epub ...
INFO:Writing Les chroniques de Bane T.10 : À la poursuite de l’amour.epub ...
INFO:Successfully downloaded file Les chroniques de Bane T.10 : À la poursuite de l’amour.epub
[olivier@thorielle adl]$ ./adl.py get -f /home/olivier/Ebook/URLLink(1).acsm
bash: erreur de syntaxe près du symbole inattendu « ( »
[olivier@thorielle adl]$ ./adl.py get -f /home/olivier/Ebook/URLLink.acsm
INFO:Opening /home/olivier/Ebook/URLLink.acsm ...
INFO:Sending fullfilment request
INFO:Downloading Les chroniques de Bane T.8 : Le grand amour de Magnus from https://kbget1-a.akamaihd.net/koboid-prod-public/editis-epub-28adc8a9-db7b-4d13-a8d7-edc9182903db.epub ...
INFO:Patching epub ...
INFO:Writing Les chroniques de Bane T.8 : Le grand amour de Magnus.epub ...
INFO:Successfully downloaded file Les chroniques de Bane T.8 : Le grand amour de Magnus.epub
[olivier@thorielle adl]$ 
```

What a pleasure not to use this essential software editor and to use Python in cli. ^\_\_\_\_\_^  
Another small stone which frees us from windaube and these filthy proprietary software. Having a choice is ...... our destiny. And down with DRM. It's really surprising (when you think you have an epub), hassle especially for one or two epub and it's the first time ....And for my........sister.

Anyway, thanks a lot for your responsiveness.

**Comment by adrienmetais** [comment]
Thanks :)
It took me quite a bit of time to reverse engineer the protocol, so I'm happy that this can be used by someone else ! :)

**Comment by olielvewen** [comment]
De rien. 
After all and by experience, you are not alone and your project helps some others people all around the world. After, it is not everybody who reports bugs and enhancement, etc ....I'm an old linux user and I'm know a bit Github too.
